### ISSUE TITLE
Add `totalCollateral` to CollateralType

### ISSUE THREAD

**Issue by wsheehan** [protofire/maker-protocol-subgraph#1]
`totalCollateral` would be the total amount of the collateral type sitting in vaults

It's very useful to know how much collateral is backing the total debt underwritten by a collateral type for leverage and market size stats, looks to me like this would be relatively easy to add?

**Comment by watersnake1** [comment]
I was also wondering why this isn't present in this subgraph. This would be very helpful!

**Comment by sistemico** [comment]
Added at 48473501449f1a8084297e2856151879175ce5fd
